name: Publish Package

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      package:
        description: "Package to publish"
        required: true
        type: choice
        options:
          - comet-uswds
          - comet-extras
          - comet-data-viz
          - comet-mcp

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci

      - name: Determine Package to Build
        id: set-package
        run: |
          PACKAGE="${{ github.event.inputs.package || 'comet-uswds' }}"
          echo "package=$PACKAGE" >> $GITHUB_OUTPUT
          echo "build_command=build:$PACKAGE" >> $GITHUB_OUTPUT

      - name: Build Package
        run: npm run ${{ steps.set-package.outputs.build_command }}

      - name: Publish Package
        run: |
          cd packages/${{ steps.set-package.outputs.package }}
          npm publish --access public
